###
@HOSTAPI=http://localhost:3000

### 
GET {{HOSTAPI}}/bor/bordispositivo HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46MTIz
x-tenancy: f3996813-838e-49af-9649-8dc44e24bc75

### 
POST {{HOSTAPI}}/bor/bordispositivo HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46MTIz

{
    "nome":"DV01xxxx",
    "numeroSerie":"123455g",
    "tipo":"E",
    "ativo":"S",
    "sysUnit":{"id":"f3996813-838e-49af-9649-8dc44e24bc75"}
}
